name: CI

on: [push]

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install
        run: yarn install --production=false

      - name: Build
        run: |
          yarn build
          yarn build-electron

      - name: Package
        run: yarn package
