name: CI

on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install
        run: yarn

      - name: Build
        run: |
          yarn build
          yarn build-electron

      - name: Package
        run: electron-builder build --mac --win -c.extraMetadata.main=build/electron/main.js --publish never
